package com.brightkey.nickfl.entities

import io.objectbox.BoxStore
import io.objectbox.BoxStoreBuilder
import io.objectbox.ModelBuilder
import io.objectbox.ModelBuilder.EntityBuilder
import io.objectbox.model.PropertyFlags
import io.objectbox.model.PropertyType


// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.
/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 *
 *
 * First steps (Android): get a builder using [.builder], call [BoxStoreBuilder.androidContext],
 * and [BoxStoreBuilder.build] to get a [BoxStore] to work with.
 */
object MyObjectBox {

    private val model: ByteArray
        get() {
            val modelBuilder = ModelBuilder()
            modelBuilder.lastEntityId(1, 7365923353334725093L)
            modelBuilder.lastIndexId(0, 0L)
            modelBuilder.lastRelationId(0, 0L)

            val entityBuilder: EntityBuilder

            entityBuilder = modelBuilder.entity("BaseUtility")
            entityBuilder.id(1, 7365923353334725093L).lastPropertyId(13, 3508901824951524934L)
            entityBuilder.flags(io.objectbox.model.EntityFlags.USE_NO_ARG_CONSTRUCTOR)
            entityBuilder.property("id", PropertyType.Long.toInt()).id(1, 4296133442264357079L)
                    .flags(PropertyFlags.ID or PropertyFlags.NOT_NULL)
            entityBuilder.property("utilityType", PropertyType.String.toInt()).id(7, 7823010918858479283L)
            entityBuilder.property("billDate", PropertyType.Date.toInt()).id(8, 1353186232877533963L)
            entityBuilder.property("dueDate", PropertyType.Date.toInt()).id(9, 4514364334017326570L)
            entityBuilder.property("datePaid", PropertyType.Date.toInt()).id(4, 4735838735568793081L)
            entityBuilder.property("amountDue", PropertyType.Double.toInt()).id(10, 1053234506758212663L)
                    .flags(PropertyFlags.NOT_NULL)
            entityBuilder.property("amountType0", PropertyType.Double.toInt()).id(11, 9138766075839801042L)
                    .flags(PropertyFlags.NOT_NULL)
            entityBuilder.property("amountType1", PropertyType.Double.toInt()).id(12, 5957551453394848768L)
                    .flags(PropertyFlags.NOT_NULL)
            entityBuilder.property("amountType2", PropertyType.Double.toInt()).id(13, 3508901824951524934L)
                    .flags(PropertyFlags.NOT_NULL)
            entityBuilder.entityDone()

            return modelBuilder.build()
        }

    fun builder(): BoxStoreBuilder {
        val builder = BoxStoreBuilder(model)
        builder.entity(BaseUtility_.__INSTANCE)
        return builder
    }

}
